# This is a basic workflow to help you get started with Actions

name: snowflake_deploy_LB

on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/deploy/**'
  workflow_dispatch:
jobs:	
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#Note the below assumes that a host path or volume is mounted into the container at ./Docker(or action will fail)!!!  
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL }} --changeLogFile=/dbscripts/masterChangelog.xml --username={{ secrets.SF_USERNAME }} --password={{ secrets.SF_PASSWORD }} --driver={{ secrets.SF_DRIVER }} --snowflakeSCHEMA=${{ secrets.SF_SCHEMA }} status

    - name: Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL }} --changeLogFile=/dbscripts/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --snowflakeSCHEMA=${{ secrets.SF_SCHEMA }} --logLevel=debug update
